name: Go (With Dagger)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Dagger Test Function
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          args: test --source=.
